SELECT
	data.[amb_temperature].value as amb_temperature,
    data.[bowl_temperature].value as bowl_temperature,
    data.[keg_temperature].value as keg_temperature,
    data.[keg_volume].value as keg_volume,
    data.[air_pressure].value as air_pressure,
    EventEnqueuedUtcTime as time,
    device_name
INTO BeerTemperature
FROM BeerIN
WHERE event_type='temperature'

SELECT 
    data.[locking1_detect_sw].value as locking1_detect_sw,
    data.[locking1_open_sw].value as locking1_open_sw,
    data.[air_pump].value as air_pump,
    data.[cooling_fan_run].value as cooling_fan_run,
    data.[locking2_detect_sw].value as locking2_detect_sw,
    data.[cooling_fan_ls].value as cooling_fan_ls,
    data.[temp_gauge_alert].value as temp_gauge_alert,
    data.[temp_gauge_backlight].value as temp_gauge_backlight,
    data.[keg_locking_led].value as keg_locking_led,
    data.[volume_gauge_backlight].value as volume_gauge_backlight,
    data.[cooling_fan_hs].value as cooling_fan_hs,
    data.[locking2_open_sw].value as locking2_open_sw,
    data.[air_pump_speed].value as air_pump_speed,
    data.[volume_gauge_alert].value as volume_gauge_alert,
    data.[defrost_coil].value as defrost_coil,
    data.[motor1].value as motor1,
    data.[motor2].value as motor2,
    data.[cooling_comp].value as cooling_comp,
    EventEnqueuedUtcTime as time,
    device_name
INTO BeerIOStat
FROM BeerIN
WHERE event_type='iostat'

SELECT 
	data.[cooling_compressor_stop] as [cooling_compressor_stop],
	data.[cooling_fan_stop] as [cooling_fan_stop],
	data.[c1_last_2l_timer] as [c1_last_2l_timer],
	data.[c1_time_max] as [c1_time_max],
	data.[c2_last_2l_timer] as [c2_last_2l_timer],
	data.[c2_time_max] as [c2_time_max],
	data.[c3_last_2l_timer] as [c3_last_2l_timer],
	data.[c3_time_max] as [c3_time_max],
	data.[calculated_total_volume] as [calculated_total_volume],
	data.[cooling_compressor_high_limit] as [cooling_compressor_high_limit],
	data.[cooling_compressor_low_limit] as [cooling_compressor_low_limit],
	data.[cooling_fan_speed] as [cooling_fan_speed],
	data.[current_keg_volume] as [current_keg_volume],
	data.[cuton_sensor] as [cuton_sensor],
	data.[debug_ambient] as [debug_ambient],
	data.[debug_fan_speed_adjust] as [debug_fan_speed_adjust],
	data.[display_debug_information_pdebug] as [display_debug_information_pdebug],
	data.[fan_pwm] as [fan_pwm],
	data.[pump_stop_work_time] as [pump_stop_work_time],
	data.[fuzy_cc_off] as [fuzy_cc_off],
	data.[fuzy_cc_on] as [fuzy_cc_on],
	data.[keg_empty_waiting_time] as [keg_empty_waiting_time],
	data.[keg_half_waiting_time] as [keg_half_waiting_time],
	data.[keg_locking_buf] as [keg_locking_buf],
	data.[keg_unlocking_buf] as [keg_unlocking_buf],
	data.[last_2l_warmup] as [last_2l_warmup],
	data.[light_brightnes_duty_value] as [light_brightnes_duty_value],
	data.[locking1_refusals_by_current_limit_cut_off as [locking1_refusals_by_current_limit_cut_off],
	data.[locking2_refusals_by_current_limit_cut_off] as [locking2_refusals_by_current_limit_cut_off],
	data.[main_frequency] as [main_frequency],
	data.[max_ambient] as [max_ambient],
	data.[max_air_value] as [max_air_value],
	data.[max_air_pump_speed] as [max_air_pump_speed],
	data.[max_rpm_pwm_fan] as [max_rpm_pwm_fan],
	data.[measured_sensor_pressure] as [measured_sensor_pressure],
	data.[min_ambient] as [min_ambient],
	data.[min_air_value] as [min_air_value],
	data.[min_rpm_pwmfan] as [min_rpm_pwmfan],
	data.[minimum_cooling_running_time] as [minimum_cooling_running_time],
	data.[minimum_cooling_stop_time] as [minimum_cooling_stop_time],
	data.[minimum_fan_running_time] as [minimum_fan_running_time],
	data.[printf_display_air] as [printf_display_air],
	data.[printf_display_final_tester_data] as [printf_display_final_tester_data],
	data.[printf_display_temp] as [printf_display_temp],
	data.[pump_run_work_time] as [pump_run_work_time],
	data.[snr] as [snr],
	data.[smart_keg_start_temperature] as [smart_keg_start_temperature],
	data.[state_locking] as [state_locking],
	data.[tapping_cycle] as [tapping_cycle],
	data.[temperature_defrost_volume] as [temperature_defrost_volume],
	data.[temperature_regulation_time] as [temperature_regulation_time],
	data.[tests_light_brightnes_duty_value] as [tests_light_brightnes_duty_value],
	data.[third_pump_stop_work_time] as [third_pump_stop_work_time],
	data.[total_count_compressor] as [total_count_compressor],
	data.[total_count_defrost_coil] as [total_count_defrost_coil],
	data.[total_count_locking1] as [total_count_locking1],
	data.[total_count_locking2] as [total_count_locking2],
	data.[total_time_defrost_coil] as [total_time_defrost_coil],
	data.[total_time_air_pump] as [total_time_air_pump],
	data.[total_time_keg_light] as [total_time_keg_light],
	data.[unlocking1_refusals_by_current_limit_cut_off] as [unlocking1_refusals_by_current_limit_cut_off],
	data.[unlocking2_refusals_by_current_limit_cut_off] as [unlocking2_refusals_by_current_limit_cut_off],
	EventEnqueuedUtcTime as time,
	device_name
INTO BeerRall
FROM BeerIN
WHERE event_type='rall'

